openapi: 3.0.3
info:
  title: HalaFood API
  version: 1.0.0
  description: HalaFood backend API documentation.

servers:
  - url: http://localhost:3000/api
    description: API base path

tags:
  - name: Categories
    description: Main categories and subcategories

paths:
  $ref: "./swagger-categories.yaml#/paths"

components:
  $ref: "./swagger-categories.yaml#/components"